name: -Actions-Workflow-V2ray-Ubuntu-

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Runs every 5 minutes.
  # Runs at 00:00 UTC every day.
  # Actions schedules run at most every 5 minutes.
  # schedule:
    # - cron: '*/5 * * * *'
    # - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run install curl
        run: |
          sudo apt update
          sudo apt-get -y install curl uuid
          curl -L -H "Connection: keep-alive" -k "https://raw.githubusercontent.com/smallflowercat1995/-Actions-Workflow-V2ray-Ubuntu-/master/getorupdatefile.sh" -o getorupdatefile.sh -O
          chmod u+x getorupdatefile.sh
          bash getorupdatefile.sh
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PW: ${{ secrets.USER_PW }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}


      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          serveraddress: smtp.163.com
          serverport: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: 创建 ssh v2ray 信息
          body: file://result.txt
          to: ${{ secrets.MAILSENDTO }}
          from: GitHub Actions
          content_type: text/html

      - name: 6h
        run: sleep 6h
